/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

/**
 *
 * @author cfp40
 */
public class PantallaAuto extends javax.swing.JPanel {

    /**
     * Creates new form Vista
     */
    public PantallaAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_Combus = new javax.swing.ButtonGroup();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Id = new javax.swing.JLabel();
        lbl_IdMarca = new javax.swing.JLabel();
        lbl_Anio = new javax.swing.JLabel();
        lbl_Estado = new javax.swing.JLabel();
        lbl_Modelo = new javax.swing.JLabel();
        lbl_Puertas = new javax.swing.JLabel();
        lbl_Buscar = new javax.swing.JLabel();
        lbl_Marca = new javax.swing.JLabel();
        spn_Puertas = new javax.swing.JSpinner();
        chk_Estado = new javax.swing.JCheckBox();
        rb_Nafta = new javax.swing.JRadioButton();
        rb_Gas = new javax.swing.JRadioButton();
        rb_Hibrido = new javax.swing.JRadioButton();
        rb_Gasoil = new javax.swing.JRadioButton();
        txt_Id = new javax.swing.JTextField();
        txt_Anio = new javax.swing.JTextField();
        txt_Buscar = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        txt_IdMarca = new javax.swing.JTextField();
        txt_Marca = new javax.swing.JTextField();
        btn_Agregar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAuto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_Combus = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_Titulo.setText("Autos");
        add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lbl_Id.setText("ID:");
        add(lbl_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 82, -1, -1));

        lbl_IdMarca.setText("ID Marca:");
        add(lbl_IdMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lbl_Anio.setText("Año:");
        add(lbl_Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 129, -1, -1));

        lbl_Estado.setText("Estado");
        add(lbl_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        lbl_Modelo.setText("Modelo:");
        add(lbl_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        lbl_Puertas.setText("Puertas:");
        add(lbl_Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lbl_Buscar.setText("Buscar:");
        add(lbl_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lbl_Marca.setText("Marca:");
        add(lbl_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));
        add(spn_Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        chk_Estado.setText("Nuevo");
        chk_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_EstadoActionPerformed(evt);
            }
        });
        add(chk_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        rb_Combus.add(rb_Nafta);
        rb_Nafta.setText("Nafta");
        add(rb_Nafta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        rb_Combus.add(rb_Gas);
        rb_Gas.setText("Gas");
        rb_Gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_GasActionPerformed(evt);
            }
        });
        add(rb_Gas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        rb_Combus.add(rb_Hibrido);
        rb_Hibrido.setText("Hibrido");
        add(rb_Hibrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        rb_Combus.add(rb_Gasoil);
        rb_Gasoil.setText("Gasoil");
        add(rb_Gasoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        txt_Id.setEditable(false);
        add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 79, 50, -1));
        add(txt_Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 126, 70, -1));

        txt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarActionPerformed(evt);
            }
        });
        add(txt_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));
        add(txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 300, -1));

        txt_IdMarca.setEditable(false);
        add(txt_IdMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 20));
        add(txt_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 150, -1));

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        btn_Borrar.setText("Borrar");
        add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        btn_Modificar.setText("Modificar");
        add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        btn_Limpiar.setText("Limpiar");
        add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        tbAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Año", "ID Marca", "Puertas", "Estado", "Combustible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAuto);
        if (tbAuto.getColumnModel().getColumnCount() > 0) {
            tbAuto.getColumnModel().getColumn(0).setMinWidth(50);
            tbAuto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbAuto.getColumnModel().getColumn(0).setMaxWidth(50);
            tbAuto.getColumnModel().getColumn(2).setMinWidth(50);
            tbAuto.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbAuto.getColumnModel().getColumn(2).setMaxWidth(50);
            tbAuto.getColumnModel().getColumn(3).setMinWidth(80);
            tbAuto.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbAuto.getColumnModel().getColumn(3).setMaxWidth(80);
            tbAuto.getColumnModel().getColumn(4).setMinWidth(50);
            tbAuto.getColumnModel().getColumn(4).setPreferredWidth(50);
            tbAuto.getColumnModel().getColumn(4).setMaxWidth(50);
            tbAuto.getColumnModel().getColumn(5).setMinWidth(50);
            tbAuto.getColumnModel().getColumn(5).setPreferredWidth(50);
            tbAuto.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 700, 220));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, -1));

        lbl_Combus.setText("Combustible:");
        add(lbl_Combus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chk_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_EstadoActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void rb_GasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_GasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_GasActionPerformed

    private void txt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JCheckBox chk_Estado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Anio;
    private javax.swing.JLabel lbl_Buscar;
    private javax.swing.JLabel lbl_Combus;
    private javax.swing.JLabel lbl_Estado;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_IdMarca;
    private javax.swing.JLabel lbl_Marca;
    private javax.swing.JLabel lbl_Modelo;
    private javax.swing.JLabel lbl_Puertas;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.ButtonGroup rb_Combus;
    private javax.swing.JRadioButton rb_Gas;
    private javax.swing.JRadioButton rb_Gasoil;
    private javax.swing.JRadioButton rb_Hibrido;
    private javax.swing.JRadioButton rb_Nafta;
    private javax.swing.JSpinner spn_Puertas;
    private javax.swing.JTable tbAuto;
    private javax.swing.JTextField txt_Anio;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_IdMarca;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_Modelo;
    // End of variables declaration//GEN-END:variables
}
