
package views;

import models.Categoria;
import models.CategoriaDao;
import models.Libro;
import models.LibroDao;
public class Pantalla extends javax.swing.JFrame {


    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_Id_Libro = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();
        txt_IdLibro = new javax.swing.JTextField();
        txt_TituloLibro = new javax.swing.JTextField();
        lbl_Autor = new javax.swing.JLabel();
        txt_AutorLibro = new javax.swing.JTextField();
        lbl_Categoria_Libro = new javax.swing.JLabel();
        txt_Categoria_Libro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Libros = new javax.swing.JTable();
        btn_Libro_Agregar = new javax.swing.JButton();
        btn_Libro_Borrar = new javax.swing.JButton();
        btn_Libro_Modificar = new javax.swing.JButton();
        btn_Libro_Limpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Categoria = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txt_IdCategoria = new javax.swing.JTextField();
        txt_NombreCategoria = new javax.swing.JTextField();
        btn_Categoria_Limpiar = new javax.swing.JButton();
        btn_Categoria_Borrar = new javax.swing.JButton();
        btn_Categoria_Agregar = new javax.swing.JButton();
        btn_Categoria_Modificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Id_Libro.setText("ID:");
        jPanel1.add(lbl_Id_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lbl_Titulo.setText("Titulo:");
        jPanel1.add(lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(txt_IdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));
        jPanel1.add(txt_TituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, -1));

        lbl_Autor.setText("Autor:");
        jPanel1.add(lbl_Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(txt_AutorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, -1));

        lbl_Categoria_Libro.setText("Categoria:");
        jPanel1.add(lbl_Categoria_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(txt_Categoria_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, -1));

        tb_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_Libros);
        if (tb_Libros.getColumnModel().getColumnCount() > 0) {
            tb_Libros.getColumnModel().getColumn(0).setMinWidth(50);
            tb_Libros.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Libros.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 460, 390));

        btn_Libro_Agregar.setText("Agregar");
        btn_Libro_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Libro_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Libro_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btn_Libro_Borrar.setText("Borrar");
        jPanel1.add(btn_Libro_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        btn_Libro_Modificar.setText("Modificar");
        jPanel1.add(btn_Libro_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btn_Libro_Limpiar.setText("Limpiar");
        jPanel1.add(btn_Libro_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jTabbedPane1.addTab("Libros", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_Categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_Categoria);
        if (tb_Categoria.getColumnModel().getColumnCount() > 0) {
            tb_Categoria.getColumnModel().getColumn(0).setMinWidth(50);
            tb_Categoria.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_Categoria.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 700, 297));

        lblId.setText("ID:");
        jPanel2.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 36, 23, -1));

        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 104, -1, -1));

        txt_IdCategoria.setEditable(false);
        txt_IdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_IdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 33, 40, -1));
        jPanel2.add(txt_NombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 101, 582, -1));

        btn_Categoria_Limpiar.setText("Limpiar");
        jPanel2.add(btn_Categoria_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        btn_Categoria_Borrar.setText("Borrar");
        jPanel2.add(btn_Categoria_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        btn_Categoria_Agregar.setText("Agregar");
        btn_Categoria_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Categoria_AgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Categoria_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        btn_Categoria_Modificar.setText("Modificar");
        jPanel2.add(btn_Categoria_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jTabbedPane1.addTab("Categorias", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 420));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(153, 204, 0));

        lbl_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Biblioteca");
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lbl_Title)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_Title)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdCategoriaActionPerformed

    private void btn_Libro_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Libro_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Libro_AgregarActionPerformed

    private void btn_Categoria_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Categoria_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Categoria_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Categoria_Agregar;
    public javax.swing.JButton btn_Categoria_Borrar;
    public javax.swing.JButton btn_Categoria_Limpiar;
    public javax.swing.JButton btn_Categoria_Modificar;
    public javax.swing.JButton btn_Libro_Agregar;
    public javax.swing.JButton btn_Libro_Borrar;
    public javax.swing.JButton btn_Libro_Limpiar;
    public javax.swing.JButton btn_Libro_Modificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbl_Autor;
    private javax.swing.JLabel lbl_Categoria_Libro;
    private javax.swing.JLabel lbl_Id_Libro;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_Titulo;
    public javax.swing.JTable tb_Categoria;
    public javax.swing.JTable tb_Libros;
    public javax.swing.JTextField txt_AutorLibro;
    public javax.swing.JTextField txt_Categoria_Libro;
    public javax.swing.JTextField txt_IdCategoria;
    public javax.swing.JTextField txt_IdLibro;
    public javax.swing.JTextField txt_NombreCategoria;
    public javax.swing.JTextField txt_TituloLibro;
    // End of variables declaration//GEN-END:variables
}
